### ISSUE TITLE
Autofocus the searchbox prop

### ISSUE THREAD

**Issue by jkcchan** [sergiop/react-giphy-searchbox#33]
Request: add prop to autofocus the select box on mount

**Comment by sergiop** [comment]
Ho @jkcchan, could you elaborate your request? What do you mean with "the select box"?

**Comment by jkcchan** [comment]
@sergiop thanks for the reply. I'm looking for a prop to autofocus the searchbox, using this HTML attribute https://www.w3schools.com/tags/att_input_autofocus.asp . The prop would toggle an `autoFocus` prop into this `input` element here: https://github.com/sergiop/react-giphy-searchbox/blob/243c54170682ffc0fe493c434f89236e6964a25a/src/components/SearchForm/SearchForm.js#L28-L36

**Comment by sergiop** [comment]
Thanks @jkcchan, now is more clear! 😉 
I didn't know this HTML attribute. Since the search input field is the only field we have inside this form, and this behavior looks always useful, I think we can simply add the `autoFocus` attribute without managing it with a prop. What do you think? I need to make some tests.
